// quiz/src/components/Tab/CatchInfo/index.tsx
import { Container } from "./style"

export const CatchInfo = ()=>{

    return(
        <Container>
            <div>
                <label htmlFor="head">Título</label>
                <input name="head" type="text"/>
            </div>
            <div>
                <label htmlFor="content">Conteúdo</label>
                <textarea name="content"/>
            </div>
        </Container>

    )
}

// quiz/src/assets/componentes/Tab/CatchInfo/CatchInfo.vue
<template>
  <div class="container">
    <div>
      <label for="title">Título</label>
      <input name="title" type="text" />
    </div>
    <div>
      <label for="content">Conteúdo</label>
      <UTextArea name="{nameTextArea}" />
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.container div {
  display: flex;
  justify-content: end;
  gap: 5px;
}

input,
textarea {
  width: 400px;
}
</style>
