// quiz/src/components/aba/aba.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'aba',
  templateUrl: './aba.component.html',
  styleUrls: ['./aba-component.css']
})
export class AbaComponent {
  title = 'aba';
  @Input() text!: string ;
  @Input() position!: number;

}

<div class="container-button">
   {{text}}
</div>

// quiz/src/components/Aba/index.tsx
import "./style.css";
export interface AbaProps {
  text: string;
  setCurrentAba: React.Dispatch<React.SetStateAction<number>>;
  position: number;
}

export const Aba = ({ text, setCurrentAba, position }: AbaProps) => {
  return (
    <div className="container-button" onClick={() => setCurrentAba(position)}>
      {text}
    </div>
  );
};
